# Меры изменчивости
Что это такое? А вот посмотрите, нижние графики примерно одинаковы и их средние и их медианы будут примерно одинаковы, тут они различаются изменьчивастью данных:

|   |   |   |   |   |   |   |   |   |
|---|---|---|---|---|---|---|---|---|
| - | - | o | - | - | o | - | - | - |
| - | - | o | o | - | o | o | - | - |
| - | o | o | o | o | o | o | - | o |

|   |   |   |   |   |   |   |   |   |
|---|---|---|---|---|---|---|---|---|
| - | - | o | o | - | o | - | - | - |
| - | - | o | o | - | o | o | - | - |
| - | - | o | o | o | o | o | - | - |


Меры изменчивости характеризуют различия между отдельными значениями выборки.

## Меры

### Размах
### $R = X_{max} - X_{min}$

Если есть длинный ряд чисел и его Xmax = 157, а Хmin = 185, то 

$R = 185-157 = 28$

Минус размаха в том, что он использует только два значения. Любое изменение очень болезненно скажется на размахе. Если мы добавим 3000 в конце, то размах из 28 станет 2843. Поэтому стоит использовать каждое значение.

### Дисперсия
Дисперсия - средний квадрат отклонений индивидуальных значений признака от их средней величины.

Дисперсия - один из способов использовать все значения для расчета. Она показывает на сколько в среднем данные отклоняются от среднего значения. 

Примерно так! [4, 5, 4, 5] 

Среднее 4,5.

Отклонения: -0.5, 0.5, -0.5, 0.5. 
> 4 - 4,5 = -0,5     
5 - 4,5 = 0,5 

Только для расчета дисперсии надо усреднить все отклонения. И тут проблема!

$-0.5 + 0.5 - 0.5 + 0.5 = 0$

$0 : n = 0$

Наше уровнение имеет вид $\Sigma^{n} _{i=1}(x_i - \overline{X})$

А как мы помним есть правило:
### $\Sigma^{n} _{i=1}(x_i - \overline{X}) = 0$  

Чтобы решить проблему надо избавиться от отрицательных значений, найдя квадрат от отклонений. Теперь выведем формулу десперсии. Нет нечего проще!

### $D = \frac{\Sigma^{n}_{i=1}(x_i-\overline{X})^2}{n-1}$ `-1 Здесь потому, что так точнее. Нам не объясили.`

### $D = \frac{\Sigma^{n}_{i=1}(x_i-M_i)^2}{n}$

У дисперсии есть одна проблема. Поскольку мы взяли квадрат, у нас сейчас тоже все в квадрате. Это нам надо решить следующей мерой.

### Среднее квадратичное отклонение

Тут слов не надо, хватит формул.

### $\sigma = \sqrt{D}$ `Тут D взят из выборки`

### $sd = \sqrt{D}$ `Тут D из генеральной совакупности.`

### Cреднее линейное отклонение

Это редко используется. но знать надо. Вместо квадрата для уничтожения отрицательных часто используют модуль:

$|-4| = 4$


$|-3500| = 3500$

## Если что-то не ясно

### Простое представление

#### $[1, 2, 2, 3, 4, 4, 5]$ 
#### $\overline{X} = 3$      
#### $n = 7$          
 $(1-3)^2 = 4$          
 $(2-3)^2 = 1$          
 $(2-3)^2 = 1$          
 $(3-3)^2 = 0$                                                    
 $(2-3)^2 = 1$          
 $(2-3)^2 = 1$          
 $(1-3)^2 = 4$     

### $D = \frac{4+4+1+1+1+1+0}{7-1} = \frac{12}{6} = 2$
### $sd = \sqrt{2} \approx 1.4$

### Сложное представлеие

Данные:

[157, 159, 161, 164, 165, 166, 167, 167, 167, 168, 169, 169, 170, 170, 170, 171, 171, 172, 172, 172, 172, 173, 173, 175, 175, 177, 178, 178, 179, 185]

Среднее значение = 170,4

Отклонения от среднего:

[-13.4, -11.4, -9.4, -6.4, -5.4, -4.4, -3.4, -3.4, -3.4, -2.4, -1.4, -1.4, -0.4, -0.4, -0.4, 0.6, 0.6, 1.6, 1.6, 1.6, 1.6, 2.6, 2.6, 4.6, 4.6, 6.6, 7.6, 7.6, 8.6, 14.6]

 Их квадрат:

[179.56, 129.96, 88.36, 40.96, 29.16, 19.36, 11.56, 11.56, 11.56, 5.76, 1.96, 1.96, 0.16, 0.16, 0.16, 0.36, 0.36, 2.56, 2.56, 2.56, 2.56, 6.76, 6.76, 21.16, 21.16, 43.56, 57.76, 57.76, 73.96, 213.16]

Сумма квадратов = 1045.2

Дисперсия = 34.84

Среднее квадратичное = 5.9

Если считать по модулю, то Среднее линейное = 4.47

## Свойства

### $D_{x+c} = D_x$

### $sd_{x+c} = sd_x$

### $D_{x*c} = D_x*c^2$

### $sd_{x*c} = sd_x*c$

<img src='№4. Меры изменчивости №1..PNG'>

## Задания

### 1. Узнать среднее отклонение ряда

In [141]:
import numpy as np

data = np.array([1, 5, 2, 7, 1, 9, 3, 8, 5, 9])

print(data)

[1 5 2 7 1 9 3 8 5 9]


In [142]:
np.mean(data)

5.0

In [143]:
data = data - 5

data

array([-4,  0, -3,  2, -4,  4, -2,  3,  0,  4])

In [144]:
data = data ** 2

data

array([16,  0,  9,  4, 16, 16,  4,  9,  0, 16], dtype=int32)

In [145]:
sd = data.sum() / len(data)

In [146]:
sd

9.0

In [147]:
np.sqrt(sd)

3.0

### 2. Как соотносятся дисперсии  двух выборок:

(1) 1 3 5 6 6 7 9 11

(2) 5 7 9 10 10 11 13 15

(Постарайтесь решить данное задание не рассчитывая значения дисперсии, но воспользовавшись одним из свойств) 

> $D_{x+c} = D_x$
#### $(1) + 4 = (2)$    
#### $D_{(1) + 4} = D_{(2)}$    
#### $D_{(1)} = D_{(2)}$   

